package titanium.desktop;
@:native("Titanium.UI.UserWindow")
extern class UserWindow {
	static var isDialog:Bool;
	static function close():String;
	@:overload(function(?options:String):UserWindow{})
	static function createWindow(?options:Dynamic):UserWindow;
	static function focus():String;
	static function getBounds():Dynamic;
	static function getChildren():Array<UserWindow>;
	static function getContextMenu():Menu;
	@:overload(function():js.Dom.Window{})
	static function getDOMWindow():Void;
	static function getHeight():Float;
	@:overload(function():String{})
	static function getIcon():Void;
	static function getID():String;
	static function getMaxHeight():Float;
	static function getMaxWidth():Float;
	static function getMenu():Menu;
	static function getMinHeight():Float;
	static function getMinWidth():Float;
	static function getParent():UserWindow;
	static function getTitle():String;
	static function getTransparency():Float;
	static function getURL():String;
	static function getWidth():Float;
	static function getX():Float;
	static function getY():Float;
	static function hasTransparentBackground():Bool;
	static function hide():String;
	static function isActive():Bool;
	static function isCloseable():Bool;
	static function isDocumentEdited():Bool;
	static function isFullscreen(chrome:Bool):String;
	static function isMaximizable():String;
	static function isMaximized():Bool;
	static function isMinimizable():Bool;
	static function isMinimized():Bool;
	static function isResizable():Bool;
	static function isTopMost():Bool;
	static function isUsingChrome():Bool;
	static function isVisible():Bool;
	static function maximize():String;
	static function minimize():String;
	static function moveTo(x:Float, y:Float):Void;
	static function open():String;
	static var openFileChooserDialog:Dynamic->Dynamic->String;
	static var openFolderChooserDialog:Dynamic->Dynamic->String;
	static var openSaveAsDialog:Dynamic->Dynamic->Void;
	static function setBounds(bounds:Dynamic):String;
	static function setCloseable(closeable:Bool):String;
	static function setContents(contents:String, ?baseURL:String):String;
	static function setContextMenu(menu:Menu):String;
	static function setDocumentEdited(edited:Bool):Void;
	static function setFullscreen(fullscreen:Bool):String;
	static function setHeight(height:Float):String;
	static function setIcon(icon:String):String;
	static function setMaxHeight(height:Float):String;
	static function setMaximizable(maximizable:Bool):String;
	static function setMaxWidth(width:Float):String;
	static function setMenu(menu:Menu):String;
	static function setMinHeight(height:Float):String;
	static function setMinimizable(minimizable:Bool):String;
	static function setMinWidth(width:Float):String;
	static function setPluginsEnabled(enabled:Bool):Void;
	static function setResizable(resizable:Bool):String;
	static function setSize(width:Float, height:Float):Void;
	static function setTitle(title:Dynamic):String;
	static function setTopMost(topmost:Bool):String;
	static function setTransparency(url:Float):String;
	static function setURL(url:String):String;
	static function setUsingChrome(chrome:Bool):String;
	static function setVisible(visible:Bool):String;
	static function setWidth(width:Float):String;
	static function setX(x:Float):String;
	static function setY(y:Float):String;
	static function show():String;
	static function showInspector(?console:Bool):String;
	static function unfocus():String;
	static function unmaximize():String;
	static function unminimize():String;
}