---
namespace: Titanium.Analytics.settingsEvent
type: function
description: Send an analytics event associated with application settings or configuration
since: 0.7.0
platforms: ['osx', 'linux', 'win32']
returns: String
parameters: 
    - [String, name, Setting name.]
    - [Object, data, Extra event data to pass along. This will be converted to JSON.]
examples:
    - description: Using Analytics.settingsEvent
      code: |
            <pre><code>
                Titanium.Analytics.settingsEvent('profile', {
                    'nickname': nickname,
                    'location': location,
                });
            </code></pre>
